server:
  port: 9090

keycloak:
  auth-server-url: http://localhost:8080/auth
  principal-attribute: preferred_username
  public-client: true
  realm: Alveola
  resource: alveola-login
  security-constraints:
    - authRoles:
        - admin-role
      securityCollections:
        - patterns:
            - /admin/*
